[Match]
Distribution=fedora

[Content]
Packages=
        bash
        coreutils
        dbus
        dnf
        passwd
        rpm
        systemd
        systemd-networkd
        systemd-pam
        util-linux
