[Match]
Distribution=rhel

[Build]
SandboxTrees=
        /etc/rhsm/ca/redhat-uep.pem:/etc/rhsm/ca/redhat-uep.pem
        /etc/pki/entitlement/:/etc/pki/entitlement/

[Content]
Packages=subscription-manager
