name: Build & Release Images

on:
  schedule:
    - cron: "15 1 * * 1"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        target:
          - distro: centos
            release: 10
          - distro: centos
            release: 9
          - distro: debian
            release: forky
          - distro: debian
            release: sid
          - distro: debian
            release: trixie
          - distro: fedora
            release: 43
          - distro: fedora
            release: rawhide
          - distro: rhel-ubi
            release: 10
          - distro: rhel-ubi
            release: 9
        arch: [x86-64, arm64]
        include:
          - arch: x86-64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Set up mkosi
        uses: systemd/mkosi@main

      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Build image
        run: mkosi -d ${{ matrix.target.distro }} -r ${{ matrix.target.release }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.target.distro }}-${{ matrix.target.release }}_${{ matrix.arch }}
          path: mkosi.output/*.*
          if-no-files-found: error
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true

      - name: Generate checksum file
        run: sha256sum * > SHA256SUMS
        working-directory: artifacts

      - name: Create release
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete latest --cleanup-tag -y || true
          gh release create latest -t "$(date -u +%F)" artifacts/*
