name: Build & Release Images

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/**
      - mkosi.conf
      - mkosi.conf.d/**
      - mkosi.nspawn
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        distro:
          - centos
          - debian
          - fedora
          - rhel-ubi
        arch: [x86_64, aarch64]
        include:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}

    env:
      OUTPUT_NAME: ${{ matrix.distro }}.${{ matrix.arch }}

    steps:
      - name: Set up mkosi
        uses: systemd/mkosi@main

      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Build image
        run: mkosi -d ${{ matrix.distro }} -o ${{ env.OUTPUT_NAME }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: mkosi.output/${{ env.OUTPUT_NAME }}.*
          if-no-files-found: error
          retention-days: 3

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: release-assets
          merge-multiple: true

      - name: Generate checksum file
        run: sha256sum * > SHA256SUMS
        working-directory: release-assets

      - name: Create release
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete latest --cleanup-tag -y || true
          gh release create latest -t "Latest build ($(date -u +'%F %R %Z'))" release-assets/*
